### ISSUE TITLE
About the Assumption 1 in Appendix

### ISSUE THREAD

**Issue by Wangt-CN** [takeshi-teshima/few-shot-domain-adaptation-by-causal-mechanism-transfer#5] opened 2020-11-26 03:23 UTC
Thanks for your great work. I have 3 questions after reading the paper a few times. 

1）The author have wrote in supp. that to meet the assumption 1, the number of source domain should be at least 2D+1, and D is the dimension of Z. So how many source domains do you use in GCL classification? (Seems only 18 ?) And this requirement can be quite hard to meet if you use a high-dimensional input feature x (e.g., 512 or 1024).

2）It seems that the number of ICs (S) is equal to the number of samples? If you have N samples in training domains, then you can get N ICs using f^-1. And ICs are independent?  

3) Why must GCL (or Non-linear ICA)? The author wrote in paper that they assume the mechanism f can be transferred. But why must use non-linear ICA? I read many times but still not very clear. It seems that any embedding method can meet the requirements.

Very appreciate for your reply. Thanks.

**Comment by takeshi-teshima** [comment] 2020-11-26 15:39
Thank you so much for your interest.
1) Yes, I must agree that the current requirement on the number of the source domains is restrictive. This condition stems from the theoretical justification of the nonlinear ICA method used as a subroutine in our paper. With that said,
  (i) Since this is only a theoretical sufficient condition (not necessarily a necessary condition), there is hope that the method still works ok in practice while validating this condition.
  (ii) The condition has the possibility to be substantially relaxed by further development of nonlinear ICA methods. The proposed method can work with any other ICA methods without making changes.
  On the other hand, I am not sure at this point if image data may have structural causal models (as in the paper) behind their distributions. (Even for other types of data such as medical records, I agree that the theoretically required number of domains is not satisfactory, and it remains to be hopefully mitigated in future work. Note that it's a theoretical requirement, and whether the method empirically works well is another question and would depend on the application instances).

2) >It seems that the number of ICs (S) is equal to the number of samples?
   Here, please note that the dimensionality of ICs is different from the number of ICs.
   The dimensionality of the IC random variables (S_1, ..., S_D) is the same as the dimensionality of the observed joint data (X, Y) (i.e., D dimensions in total), which is an assumption coming from the structural causal model. On the other hand, the number of the estimated IC values ((S_1^(i), ..., S_D^(i)) is $N$ (one set for each target domain data point).
   Here's another attempt to make the explanation clearer: I think it helps to distinguish between ICs as random variables and the realized values of ICs. The number of ICs (as random variables) is $D$. On the other hand, the number of the realized values of ICs is $N$ (since one set of IC values is obtained for each joint data point (X_i, Y_i)). In total, we are estimating $N \times D$ values during the IC estimation step.
    The independence assumption is on the IC random variables (S_1, ..., S_D).
    The "value-exchanging" procedure after the IC estimation step is motivated by this independence, but it had to be separately given a theoretical guarantee since the estimated ICs are not exactly the original ICs (since we use the estimated f) hence the independence may not hold for these "estimated IC" random variables. Still, the validity of this procedure is confirmed through the theorems.

3) The uniqueness of nonlinear ICA is that they provide "identifiability" of $f$. Even after we assume that the underlying $f$ is transferrable, whether we can estimate $f$ correctly /accurately is a different difficult question. Not all embedding methods can do that, and the nonlinear ICA methods have been developed (by the respective researchers) exactly for that purpose: estimating $f$. That is why we needed a nonlinear ICA method in our paper, but if there are other methods that have the ability to estimate the true $f$, I believe it can be also used.

I hope those answer your questions! Please do not hesitate to ask again if the above are unclear or if you have further questions. :)

**Closed as completed** 2021-04-28 10:58 UTC
